"""Module 5: attendance and student_predictions

Adds the two tables Module 5 (ML risk prediction) needs:
- `attendance_records`: one faculty-entered attendance percentage per
  (course, student) -- the only XGBoost feature with no prior source.
- `student_predictions`: per-student risk level + confidence + predicted score
  + SHAP payload (CLAUDE.md sections 6 & 9), treated as derived data.

The `risk_level` enum is created automatically as part of `create_table`
(unlike an enum column added to an existing table, which needs an explicit
`.create()`), but Alembic will not drop it on downgrade -- handled below.

Revision ID: 2e8ce4e237b9
Revises: 48e8e934eaba
Create Date: 2026-08-15 15:48:44.859604

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2e8ce4e237b9'
down_revision: Union[str, None] = '48e8e934eaba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('attendance_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('attendance_percentage', sa.Float(), nullable=False),
    sa.CheckConstraint('attendance_percentage >= 0 AND attendance_percentage <= 100', name='ck_attendance_percentage_range'),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('course_id', 'student_id', name='uq_attendance_course_student')
    )
    op.create_table('student_predictions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('risk_level', sa.Enum('low', 'medium', 'high', name='risk_level'), nullable=False),
    sa.Column('confidence_score', sa.Float(), nullable=False),
    sa.Column('predicted_score', sa.Float(), nullable=False),
    sa.Column('shap_explanation', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('student_id', 'course_id', name='uq_prediction_student_course')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('student_predictions')
    op.drop_table('attendance_records')
    # ### end Alembic commands ###

    # Alembic does not drop the enum type it created with the table, which
    # would make a subsequent upgrade fail with "type already exists" (same
    # fix the Module 3 migration applies to `assessment_type`).
    sa.Enum(name='risk_level').drop(op.get_bind(), checkfirst=True)
