"""Faculty modules: course uniqueness, question types, question uniqueness

Revision ID: c3af4f47a354
Revises: b6f4d2a91c73
Create Date: 2026-08-12 00:07:59.837102

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c3af4f47a354'
down_revision: Union[str, None] = 'b6f4d2a91c73'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('courses_code_key'), 'courses', type_='unique')
    op.create_unique_constraint('uq_course_program_code_semester', 'courses', ['program_id', 'code', 'semester'])
    # Autogenerate emits `ADD COLUMN ... question_type` assuming the enum type
    # already exists, but a standalone ADD COLUMN (unlike CREATE TABLE) does
    # not create it -- must be created explicitly first (see HANDOFF.md §9).
    question_type_enum = sa.Enum(
        'question', 'mcq', 'fill_blank', 'true_false', 'project', 'lab', name='question_type'
    )
    question_type_enum.create(op.get_bind(), checkfirst=True)
    op.add_column('questions', sa.Column('question_type', question_type_enum, server_default='question', nullable=False))
    op.add_column('questions', sa.Column('type_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.create_unique_constraint('uq_question_assessment_number', 'questions', ['assessment_id', 'question_number'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_question_assessment_number', 'questions', type_='unique')
    op.drop_column('questions', 'type_data')
    op.drop_column('questions', 'question_type')
    op.drop_constraint('uq_course_program_code_semester', 'courses', type_='unique')
    op.create_unique_constraint(op.f('courses_code_key'), 'courses', ['code'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
    # Autogenerate doesn't drop enum types on downgrade (see HANDOFF.md §9) --
    # the column is gone above, but the `question_type` Postgres enum type
    # itself would otherwise linger.
    sa.Enum(name='question_type').drop(op.get_bind(), checkfirst=True)
