"""Module 3: assessments, questions, scores, enrollments, attainment

Revision ID: ea0d9492afbe
Revises: 0738261f68d0
Create Date: 2026-08-05 20:31:25.621240

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ea0d9492afbe'
down_revision: Union[str, None] = '0738261f68d0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assessments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('type', sa.Enum('quiz', 'assignment', 'lab', 'midterm', 'final', name='assessment_type'), nullable=False),
    sa.Column('total_marks', sa.Float(), nullable=False),
    sa.Column('weightage_percent', sa.Float(), nullable=False),
    sa.Column('date', sa.Date(), nullable=True),
    sa.CheckConstraint('total_marks >= 0', name='ck_assessment_total_marks'),
    sa.CheckConstraint('weightage_percent >= 0 AND weightage_percent <= 100', name='ck_assessment_weightage'),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('course_enrollments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('course_id', 'student_id', name='uq_course_student')
    )
    op.create_table('attainment_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('clo_id', sa.Integer(), nullable=False),
    sa.Column('attainment_percentage', sa.Float(), nullable=False),
    sa.Column('is_achieved', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['clo_id'], ['clos.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('student_id', 'course_id', 'clo_id', name='uq_attainment_scope')
    )
    op.create_table('questions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('assessment_id', sa.Integer(), nullable=False),
    sa.Column('question_number', sa.Integer(), nullable=False),
    sa.Column('marks', sa.Float(), nullable=False),
    sa.Column('clo_id', sa.Integer(), nullable=True),
    sa.Column('text', sa.Text(), nullable=True),
    sa.CheckConstraint('marks >= 0', name='ck_question_marks'),
    sa.ForeignKeyConstraint(['assessment_id'], ['assessments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['clo_id'], ['clos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('student_scores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('marks_obtained', sa.Float(), nullable=False),
    sa.CheckConstraint('marks_obtained >= 0', name='ck_score_non_negative'),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('question_id', 'student_id', name='uq_question_student')
    )
    op.add_column('courses', sa.Column('attainment_threshold', sa.Float(), server_default='50.0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('courses', 'attainment_threshold')
    op.drop_table('student_scores')
    op.drop_table('questions')
    op.drop_table('attainment_records')
    op.drop_table('course_enrollments')
    op.drop_table('assessments')
    # ### end Alembic commands ###

    # Alembic does not drop the enum type it created, which would make a
    # subsequent upgrade fail with "type already exists".
    sa.Enum(name='assessment_type').drop(op.get_bind(), checkfirst=True)
